
source $HOME/code/secrets/tokens.sh
source $HOME/code/secrets/osx-tokens.sh
source $HOME/code/secrets/env.sh
source $HOME/.bash_aliases

BREW_PREFIX=`brew --prefix`

# Get rid of/alias to docker images soon
export PATH=$PATH:/Applications/mongodb/bin
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.4/bin
export PATH=$PATH:/Users/cjones/Library/Android/sdk/platform-tools/

export ANDROID_HOME=$HOME/Library/Android/sdk
#export ANDROID_HOME=/usr/local/opt/android-sdk
export PYTHONPATH=$BREW_PREFIX/lib/python2.7/site-packages:$PYTHONPATH

export CLICOLOR=1
export LSCOLORS=gxFxCxDxBxegedabagaced
